name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: openccgo
          BINDIR: dist
        run: make -j releases

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          draft: true
          prerelease: true
